### ISSUE TITLE
How to generate case without hull like pcb does?

### ISSUE THREAD

**Issue by meteozond** [50an6xy06r6n/hotswap_pcb_generator#14]
I want to make ymdk sp84  clone, but found that case is generated with hull, is it possible to override this behaviour?

![image](https://user-images.githubusercontent.com/975689/145678156-b07c4b9a-f0bf-43c3-a11b-088abd166744.png)

![image](https://user-images.githubusercontent.com/975689/145678289-80f82ced-c15f-4c10-a7c4-c23a8f55761f.png)

**Comment by 50an6xy06r6n** [comment]
Check out the documentation for `base_plate_layout` and `use_plate_layout_only` in `scad/README.md`. There's an example of how to use them in `scad/default_layout.scad`.
