### ISSUE TITLE
Backplate not generating correctly

### ISSUE THREAD

**Issue by smolbun** [50an6xy06r6n/hotswap_pcb_generator#16]
I'm trying to generate the backplate using the jd40 example but I'm not sure what's wrong it

![backplate](https://user-images.githubusercontent.com/45829953/161438439-d43784cd-e0c6-4409-80db-dc14097fbb8d.png)

[scad.zip](https://github.com/50an6xy06r6n/hotswap_pcb_generator/files/8405039/scad.zip)

**Comment by AndyChiu** [comment]
Tenting?
![image](https://user-images.githubusercontent.com/1038943/161439275-2e224328-2e90-4a80-98a2-ea95a3c5be30.png)

**Comment by smolbun** [comment]
> 
ah that solves it, sorry It's my first time with openscad. How do you generate screw points to mount the backplate to the case of the keyboard?

**Comment by AndyChiu** [comment]
hi, you can read this guide, and find Standoff Placement part
https://github.com/50an6xy06r6n/hotswap_pcb_generator/blob/main/guide/design_guide.md

**Comment by smolbun** [comment]
I got it to work :) , didn't know I had to specify the location of the standout manually 

![image](https://user-images.githubusercontent.com/45829953/161816588-960e5307-0e2b-4d93-8ccc-5ca1b444bc78.png)

[jd40_scad.zip](https://github.com/50an6xy06r6n/hotswap_pcb_generator/files/8420636/jd40_scad.zip)
