### ISSUE TITLE
Autofill stabilizers layout

### ISSUE THREAD

**Issue by eduhoribe** [50an6xy06r6n/hotswap_pcb_generator#19]
I made a pretty simple implementation just to scratch my own itch, but it's far from perfect, feedback appreciated.

**Comment by 50an6xy06r6n** [comment]
If you still care about this, maybe open up a PR? Logic seems ok, if a little brittle, but everything in this project is pretty brittle anyway.

**Comment by eduhoribe** [comment]
I would be happy to open a PR. Just updated my fork and did a quick review on my commit.
Did some minor changes to make it work after the latest changes in the repo.
