### ISSUE TITLE
Add support for solid cases

### ISSUE THREAD

**Issue by 50an6xy06r6n** [50an6xy06r6n/hotswap_pcb_generator#7]
I think integrated-plate cases are feasible, and could be a nice feature to have for more permanent solutions.

**Comment by AndyChiu** [comment]
Hi, the generator is feasible create like this keyboard case ? have around wall
https://github.com/rtitmuss/torn/blob/master/case/HiPro%20Case/readme.md

**Comment by 50an6xy06r6n** [comment]
What I'm thinking is less complicated. Would probably be integrated with the plate or backplate

**Comment by AndyChiu** [comment]
It's Great!

**Comment by AndyChiu** [comment]
This have some idea 
https://github.com/takjn/kbcgen

**Comment by 50an6xy06r6n** [comment]
Thanks, that gave me some ideas on how to make plate shape generation prettier overall.

**Comment by 50an6xy06r6n** [comment]
Started working on it in the [solid_case](https://github.com/50an6xy06r6n/hotswap_pcb_generator/tree/solid_case) branch

**Comment by 50an6xy06r6n** [comment]
Merged solid case code into main and added example STLs
